# Generated by Django 5.1.4 on 2024-12-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_cart_order_alter_cart_quantity_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='status',
            field=models.BooleanField(default=False, help_text='False - Visible, True - Hidden'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='trending',
            field=models.BooleanField(default=False, help_text='False - Default, True - Trending'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, help_text='False - Visible, True - Hidden'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='False - Default, True - Trending'),
        ),
    ]
